name: Trigger auto deployment for octopetsfe

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/octopetsfe-AutoDeployTrigger-a1a58a6a-20c2-4a69-b5f6-ec485f4fde95.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.OCTOPETSFE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OCTOPETSFE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OCTOPETSFE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acr5ve6wfidni45i.azurecr.io
          registryUsername: ${{ secrets.OCTOPETSFE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OCTOPETSFE_REGISTRY_PASSWORD }}
          containerAppName: octopetsfe
          resourceGroup: rg-sretest
          imageToBuild: acr5ve6wfidni45i.azurecr.io/octopetsfe:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


